apiVersion: v1
kind: Service
metadata:
  name: {{ include "cgwi-php.fullname" . }}-redis
  labels:
    component: cache
    {{- include "cgwi-php.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports: 
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    component: cache
    {{- include "cgwi-php.selectorLabels" . | nindent 4 }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cgwi-php.fullname" . }}-redis
  labels:
    component: cache
    {{- include "cgwi-php.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "cgwi-php.fullname" . }}-redis
      component: cache
      {{- include "cgwi-php.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "cgwi-php.fullname" . }}-redis
        component: cache
        {{- include "cgwi-php.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cgwi-php.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: redis:alpine3.18
          command:
            - /bin/sh
            - -c
            - redis-server --requirepass ${REDIS_PASSWORD:?Need to set REDIS_PASSWORD env var}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "cgwi-php.fullname" . }}-redis
          volumeMounts:
            - name: redis-data
              mountPath: /data
              subPath: redis
          resources:
            limits:
              memory: 256Mi
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: backups-{{ include "cgwi-php.fullname" . }}
