apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cgwi-php.fullname" . }}-app
  labels:
    {{- include "cgwi-php.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi