{{- if .Values.route.enabled -}}
{{- $fullName := include "cgwi-php.fullname" . -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "cgwi-php.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- else }}
  subdomain: {{ $fullName }}
  {{- end }}
  tls:
    {{- toYaml .Values.route.tls | nindent 4 }}
  path: /
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ $fullName }}
{{- end -}}