apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cgwi-php.fullname" . }}-app
  labels:
    {{- include "cgwi-php.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secrets.app | nindent 2}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cgwi-php.fullname" . }}-mysql
  labels:
    {{- include "cgwi-php.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_HOST: {{ include "cgwi-php.fullname" . }}-mysql
  {{- toYaml .Values.secrets.mysql | nindent 2}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cgwi-php.fullname" . }}-redis
  labels:
    {{- include "cgwi-php.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_HOST: {{ include "cgwi-php.fullname" . }}-redis
  {{- toYaml .Values.secrets.redis | nindent 2}}
{{ if .Values.secrets.s3backup.BUCKET -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cgwi-php.fullname" . }}-s3backup
  labels:
    {{- include "cgwi-php.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secrets.s3backup | nindent 2}}
{{- end -}}