apiVersion: v1
kind: Service
metadata:
  name: {{ include "cgwi-php.fullname" . }}-mysql
  labels:
    {{- include "cgwi-php.labels" . | nindent 4 }}
    component: database
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
      port: 3306
  selector:
    {{- include "cgwi-php.selectorLabels" . | nindent 4 }}
    component: database

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "cgwi-php.fullname" . }}-mysql
  labels:
    {{- include "cgwi-php.labels" . | nindent 4 }}
    component: database
spec:
  selector:
    matchLabels:
      component: database
      {{- include "cgwi-php.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "cgwi-php.fullname" . }}-mysql
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        component: database
        {{- include "cgwi-php.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cgwi-php.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "mysql:8.0"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "cgwi-php.fullname" . }}-mysql
          resources:
            limits:
              memory: 512Mi
          volumeMounts:
          - name: dbdata
            mountPath: /var/lib/mysql
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: dbdata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
